### PR TITLE
Switch to GHA

### PR DESCRIPTION
**Pull request by cderv**
Same as others. 

* 3 OS
* R CMD CHECK from r-lib/actions without much customization
* Ubuntu bionic as on travis. 3 R version as on travis.

I added an individual workflow to run the test-packages.R that checks the different projects to identify required LateX packages to include. We may not need to run this one at each PR.

### CODE REVIEW

**Comment by cderv** [comment]
This is now working. 
I had to modify the `test-packages.R` script because workspace folders where different, and calling `tlmgr path add` in the R script was not working - PATH was not modified and `tlmgr` not found. That is why `TinyTeX-0` (base installation) is installed using `r-lib/actions/setup-tinytex`

Not sure why it is taking a long time to run. Maybe because it was the first time... 

I left appveyor on the side as it is working. We could build the release on GHA too if we want. 

@yihui I let you merge this one as I touched some of your infrastructure file. I think this is working as before but I don't use `install-base.sh` anymore.

**Review by yihui — APPROVED** [review]
It's okay to use TinyTeX-0 instead of `install-base.sh`.

The main thing I'm thinking about is if it's worth using three workflows. I feel there is too much repetition, although the yaml files might have been generated automatically. I'm wondering if this is going to be difficult to maintain. The original `.travis.yml` has 22 lines of config, and the new GHA yaml files have 223 lines of config :)

Anyway, I'm merging this PR for now. We may consider merging the workflows in the future. Thanks!

**Comment by cderv** [comment]
I agree and I was wondering if you would make this remark. I understood you like concise code : less lines, less errors, easier to maintain. 

I concluded that travis has less lines because of the "black box": all the caching, installing, building, checking where hard-coded in travis support for R whereas for GHA it is no black box and you need to code it yourself. More lines, but more freedom. We also are testing on 3 OS againt one before. 

I believe this is separate because you don't want to have the coverage run for all your job matrix defined in R-CMD-CHECK. But I think we could add the coverage stuff as a step after the checking in case of success using a `if` on this step to be only run on [Linux - R release] for example (and not by each job defined in matrix).

For the required latex package, we could do the same. I thought it was something different than checking so it feels ok to have it on the side, but there is indeed a lot of duplication.

When I thought about that, I wondered if using docker would be interesting too. We could have images setup shared for our repos that we could use in each of those workflow - maintaining container to be used in several places. But currently, I am not convinced by the gain. 

Anyway, I'll try something in here to see if having only one workflow would work better. I don't mind doing the maintenance of all this. Feel free to ping me anytime there is something odd in a GHA workflow and I'll look into it.

**Comment by yihui** [comment]
Okay. Thanks for the explanation! I definitely don't want to spend too much time on this, given that it's working well. I'll leave it aside for now, and may revisit it in the future if a real problem occurs.

**Pull request merged**
