### PR TITLE
Retry download with Powershell if it has error

### PR DESCRIPTION
**Pull request by cderv**
This PR tries to solve #270 by adding a retry mechanism if download fails. 

This is done in BAT by looking at the error code and retrying 5 times if there is an issue. 
If it does not work, it will also error properly, which is not the case now. 

the `powershell` code will indeed error, but the current `bat` file does not handle this error, and I believe that is why the `setup-tinytex` action does not properly error. (https://github.com/r-lib/actions/issues/213)
The action does [correctly try-catch](https://github.com/r-lib/actions/blob/a76196994633e92987350cb0bce04050a89d3f50/setup-tinytex/src/setup-tinytex.ts#L117) but our BAT file does not send an error from the powershell command. 

Is the `pause` command important also ? 
https://github.com/yihui/tinytex/blob/82e76dc7ac955cc7e160d80a4c97086ea4117d4f/tools/install-bin-windows.bat#L29

I have tested this locally and it works for me. I did not yet tested in on GHA. 

@yihui does it seem ok to you ? Merging will impact everyone using this script so I prefer having a second pair of eye on this. Thanks! 

Also a related question: is there a specific reason to have use `Invoke-WebRequest` ? 

It seems it is not the only method and not the best, one of the cons being (source is a bit old but still)
> Cons
Speed. This cmdlet is slow. From what I have observed, the HTTP response stream is buffered into memory. Once the file has been fully loaded, it is flushed to disk. This adds a huge performance hit and potential memory issues for large files.

Source: https://blog.jourdant.me/post/3-ways-to-download-files-with-powershell

We could try also this one: 
```powershell
powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;(New-Object System.Net.WebClient).DownloadFile($Env:TINYTEX_URL, 'install.zip')"
```

This works well. [doc](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient) says that now [`System.Net.Http.HttpClient class`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) but it could be too recent for being supporting in Powershell 5 by default. Did not try yet. 

I am wondering all that because having a powershell install script could be intesting.

### CODE REVIEW

**Review by yihui — COMMENTED** [review]
> If it does not work, it will also error properly

That's great!

> Is the `pause` command important also ?

Not very important. It's only for users who download and run the `.bat` script locally, so they could see the details before the script exits. I'm okay with removing it.

> is there a specific reason to have use `Invoke-WebRequest` ?

> This works well. [doc](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient) says that now [`System.Net.Http.HttpClient class`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) but it could be too recent for being supporting in Powershell 5 by default.

Is there a way to test the version of PowerShell and use the new download method conditionally? I guess GHA might have a newer version of PowerShell (v5 was released in Jan 2017), and the main problem we want to solve here is for GHA, so it may be a better idea to try the new download method first. You may open another PR, and also leave this one open here. I'd like to check if the alternative download method works before we use this retrying mechanism. Thanks!

**Comment by cderv** [comment]
> I guess GHA might have a newer version of PowerShell (v5 was released in Jan 2017),

GHA has powershell 7 which what I use locally too. 
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#powershell-tools

I think `(New-Object System.Net.WebClient).DownloadFile()` would work as an alternative to `Invoke-Request`. 
The new `System.Net.Http.HttpClient` class use a logic of Async stream so the code is more complex (as longer) - as we are using powershell command as one liner, the format could be easier to use.

**Comment by cderv** [comment]
It seems Powershell 5 requires .NET 4.5 (https://docs.microsoft.com/fr-fr/powershell/scripting/windows-powershell/install/windows-powershell-system-requirements?view=powershell-7.1#microsoft-net-framework-requirements) and it seems it has been introduced in this version of .NET (from this [article](https://www.infoworld.com/article/3198673/when-to-use-webclient-vs-httpclient-vs-httpwebrequest.html#:~:text=In%20a%20nutshell%2C%20WebRequest%E2%80%94in,and%20posts%2C%20having%20arrived%20with%20.) and [microsoft doc](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.5), so it should work ok without testing Powershell version unless we want to support very old installatio for non R user.

I'll make another PR with this

**Comment by cderv** [comment]
I'll close this for now in favor of #276 

We'll reopen if needed.

**Pull request closed without merging**
