### PR TITLE
Build TinyTeX bundles on GHA

### PR DESCRIPTION
**Pull request by cderv**
Aim is to switch from using Appveyor.

### CODE REVIEW

**Comment by cderv** [comment]
Github action is done again but I believe this working for Windows now. 

Among questions I have: 

* Can I set appveyor to only build on master so that is not trigger by this PR ? Currently, it seems it builds on PR too... 
https://ci.appveyor.com/project/yihui/tinytex/builds/42992448 
   * I believe it made sense in the past where appveyor was also testing the package right ? 
 
* When do we want to trigger a build of all bundles ? 
  * At least Daily right ? 
  * But also on push to master on PR ? not sure...

* We want to keep the publishing of all bundles to github release right ? 

* I am using the current state of repo for installing tinytex R package in this workflow, but do we want CRAN version instead ? I don't think so but I may be missing something.

once GHA is back up again, I'll add Linux and Mac build

**Comment by cderv** [comment]
Workflow is now updated for all OS. Hopefully it is working but I can't try for now - github actions needs to go back up. 

Structure is the following

* 1 jobs per OS that will run in parallel
* All jobs are doing the following the same: checkout code, install pandoc, install R, install tinytex and its dependencies
* Then jobs differs in the way they do it the following: 
  * Install infra only and build TinyTeX-0
  * Install more CTAN package from `pkg-custom.txt` and bundle TinyTeX-1
  * Install more packages from `test-basic.R` and bundle TinyTeX
* On Linux only, 
  * Export regex-json
  * *nix installer is packaged
* And lastly, tinitex is built on all OS using `build-tinitex.R`

All this is done using the same scripts than in appveyor. No much changes in the way it is done to avoid breakage. 

There will be a last job, that runs after all others have succeeded to deploy the bundles. In each jobs, bundles are saved as artifacts  and then this last job will simply retrieve everything and publish to github release. I'll wait to check that everything is working before doing this.

**Comment by cderv** [comment]
@yihui , to work on the release process I set it up in my fork. 

Here is what have been created automatically:  https://github.com/cderv/tinytex-releases/releases

It seems I am missing TinyTeX-2* builds - where are they built ? I don't see them in appveyor 🤔 

The workflow file modified for this to work is here : https://github.com/yihui/tinytex/compare/appveyor-gha-switch...cderv:appveyor-gha-switch

I am currently checking that publishing again will correctly overwrite the current created release.

Before updating the branch here, one question: On which condition do we want to publish ? 
You said to run the workflow daily and on push to main 
> Yes (daily) and yes (also push to main).

but we want to deploy only on daily build right ? Or you want to publish every time ? 

Happy to discuss this over a call to validate all this change.

**Comment by yihui** [comment]
You can ignore TinyTeX-2 for this PR and work on it later. Currently it's built daily in the tinytex-releases repo: https://github.com/yihui/tinytex-releases/blob/master/appveyor.yml This might be a trickier task for you. The last time when I tried, I ran into some obscure errors when installing `scheme-full`.

> but we want to deploy only on daily build right ? Or you want to publish every time ?

Either way is okay, whichever way you think is easier. I guess it doesn't make much difference for TinyTeX, -1, and -0 bundles. Only TinyTeX-2 matters because it takes a long time (~45min on Windows), and we probably don't want to rebuild it on every push but just schedule daily builds for it.

**Comment by cderv** [comment]
> You can ignore TinyTeX-2 for this PR and work on it later.

ok ! I didn't know you could add an assets in another step. I'll do that later. 

> I am currently checking that publishing again will correctly overwrite the current created release.

I can confirm it worked ! 🎉 
Assets are deleted (https://github.com/cderv/tinytex/runs/5678535156?check_suite_focus=true#step:5:16) and release is updated (new time in https://github.com/cderv/tinytex-releases/releases)

> Either way is okay, whichever way you think is easier

Either way is easier. It is just a matter of the `if:` I put in the last jobs. Either no if and every successful run will update the release, Either deploying only on scheduled daily job. 

Personally, I think building and deploying once a day is enough for those bundles that we call daily. I am not quite sure why we could need to run this at each push. However, if do run this workflow at each push then, we can surely deploy as it is not a costly step. 

In order to finish this, the repo require a setting. Can you set create a GITHUB TOKEN and put in secrets in this repo ? 
Using name for this secrets: `${{ secrets.CUSTOM_GITHUB_TOKEN }}`. This is required to publish the release in the other repo as the default `GITHUB_TOKEN` won't have the correct access right. I don't have access to settings here to do it.

Another question: If everything is building correctly on the CI we can assume that the bundles created are ok right ? 
Do you want to test them separately ? I did a quick `tinytex:::install_prebuilt()` to check the TinyTeX bundles.

**Comment by cderv** [comment]
> Is it possible to delete and upload assets one by one (e.g., using gh)? 

Currently I am using a action (https://github.com/softprops/action-gh-release) that does the work for us so I am not using gh directly. Currently, it seems assets are deleted then uploaded https://github.com/cderv/tinytex/runs/5678535156?check_suite_focus=true#step:5:16

Other actions exists for this so I can look to see if they work the same. 

We could also do our own step using the gh CLI tool if we want this. We indeed have a specific usage of this pre-release tag. I don't know what happens if download happens at the same time as upload. Probably the upload is blocked ? A question for Github Community maybe ...

> I've thought of creating a temporary tag, e.g., daily2, uploading assets to that tag, and then renaming it to daily. This might solve the problem.

This could indeed by a solution to the problem

> That sounds like a good idea. It seems you haven't pushed it? I didn't see it in the workflow file.

I have done that locally to check that the new built bundles are working. The only check done in workflow is installing TinyTeX-0 for each OS. 
Example for Windows: 
https://github.com/yihui/tinytex/blob/1d569064dfb476452c661ba8b6f627af2f1050cc/.github/workflows/build.yaml#L63-L67

Same as install_prebuilt() right ? 

Currently this branch in this repo is not updated to the deployment face (so that I don't update by mistake the current release 😅 )

**Comment by yihui** [comment]
It will be great if you can check what happens if you download an asset when it is being deleted from a release. I guess the download may fail. Releasing to a temporary tag and renaming that tag to `daily` may be the safest way to go.

**Comment by cderv** [comment]
> It will be great if you can check what happens if you download an asset when it is being deleted from a release.

I'll try to coordinate the action with the workflow step 😅 

> Releasing to a temporary tag and renaming that tag to daily may be the safest way to go.

We would still have to delete the previous release and then rename the new one ? 
Or does just moving the tag would work ? I wonder what happens in the releases page in that case 🤔

**Comment by yihui** [comment]
> We would still have to delete the previous release and then rename the new one ?
> Or does just moving the tag would work ?

My guess is that if we rename the temporary tag to `daily` and force push the `daily` tag to override the previous `daily` tag, everything should work without interruption.

> Maybe draft release if what we need

How would a draft release solve the problem?

**Comment by cderv** [comment]
> How would a draft release solve the problem?

I see that as making a new temporary tag then renaming and force pushing. Instead we create the draft release for daily tag, this does not override the current release for daily, then when everything is upload, we can safely undraft the release which would replace the daily tag release. 

Seems like similar but without new temp tag. Unless pre-release and draft are uncompatible... 

Do you thing I am missing something ?

**Comment by yihui** [comment]
I just tested it and found that draft release could use the same tag as other releases. I didn't know that. However, I also find that when you undraft the release, you will still have to delete the existing `daily` release. That said, I think the potential interruption time should be fairly short, since deleting an existing release and publishing a draft release should be quick. So yes, please go ahead and create a draft release with the `daily` tag, delete the existing `daily` release, and publish te draft release.

**Comment by cderv** [comment]
Cool. Thank you for testing ! I'll switch back to this subject now so I should have something for later today.

**Comment by cderv** [comment]
Just for the record as notes, `gh` CLI does not allow us yet to edit a release, and so to undraft a release (I believe this will be covered by https://github.com/cli/cli/issues/1997). So to follow this IDE we need another way (API or rerunning the publish action maybe...).

**Comment by cderv** [comment]
For the record we are at 23 min for builds and deploy. Windows is the longest. 
* https://github.com/cderv/tinytex/actions/runs/2059126460
* https://github.com/cderv/tinytex-releases/releases

**Comment by cderv** [comment]
I have updated this PR now. 
  
  Only thing left to do before going live 

- [ ] change repo to deploy too to `yihui/tinytex-releases`
- [ ] Reactivate the depoyment steps
- [ ] Uncommand trigger on schedule

**Review by yihui — APPROVED** [review]
Okay, everything you did looks good to me now. Please feel free to move on. Thanks!

**Comment by cderv** [comment]
Following merge I triggered a manual deploy and this works fine ! 
* https://github.com/yihui/tinytex/runs/5751454636?check_suite_focus=true
* https://github.com/yihui/tinytex-releases/releases/tag/daily

**Comment by yihui** [comment]
Perfect! Thanks! Next you can try to build `texlive-full` when you have time.

**Pull request merged**
